Created scripting/API/overview.md (ZH)
HakuyaLabs/warudo-docs pull request #80
Opened 2024-10-06 03:04 UTC by EcoFur

2024-10-06 09:03 UTC, EcoFur commented
I translated:
>scripting/API/overview  
<br>
I’ll translate more in future.

2024-10-06 15:35 UTC, EcoFur commented
Translated
>mocap/steamvr.md

2024-10-20 03:15 UTC, TigerHix commented
翻译辛苦，给了初步的code review，有空的时候麻烦修正一下，感谢~

2024-10-20 10:03 UTC, EcoFur commented
不太理解句意……可以重发一遍吗？
I don't understand the meaning......Emm..........You can also sent in Englishi.

2024-10-20 10:11 UTC, TigerHix commented
code review=代码审核。[https://github.com/features/code-review](https://github.com/features/code-review)

简单来说给代码提出了要修改的地方，点[这里](https://github.com/HakuyaLabs/warudo-docs/pull/80/files)查看全部我写的评论。

2024-10-20 10:27 UTC, EcoFur commented
![IMG_8695](https://github.com/user-attachments/assets/75fa6149-96c1-453f-b9b6-e1131ff81aaa)
![IMG_8696](https://github.com/user-attachments/assets/655f4548-50f1-4ab4-8346-8685cbc6a475)
……我没看到任何变化……………对不起，我是第一次提交PR，还不熟悉PR流程，没找到你的Code Review

2024-10-20 10:32 UTC, EcoFur commented
我去上学了，下周再搞了……呜

2024-10-26 15:37 UTC, EcoFur commented
> code review=代码审核。https://github.com/features/code-review
> 
> 简单来说给代码提出了要修改的地方，点[这里](https://github.com/HakuyaLabs/warudo-docs/pull/80/files)查看全部我写的评论。

对不起，我仔细翻阅了这个PR的每个角落，没有发现任何的变化。

2024-10-30 22:17 UTC, TigerHix requested changes

2024-10-30 22:17 UTC, TigerHix commented
现在应该有了！

2024-10-31 03:10 UTC, EcoFur commented
Ok, tiger. 明天晚些仔细看下。😁


Sent from my Apple Watch

2024-10-31 05:01 UTC, EcoFur commented
有个问题，蓝图里的变量都是直接显示的脚本变量，如果脚本中不改用中文变量，有什么方法在蓝图里显示中文？


Sent from my Apple Watch

2024-11-01 11:11 UTC, EcoFur commented on i18n/zh/docusaurus-plugin-content-docs/current/scripting/API/entities.md
> +- **结构数据：** 继承 `StructuredData` 来创建新的 [结构体](structured-data) 。结构体是一种复杂的数据类型，可用作节点、资产或插件中的“嵌入式”数据输入。
统一 结构数据

2024-11-01 12:15 UTC, EcoFur commented on i18n/zh/docusaurus-plugin-content-docs/current/scripting/API/entities.md
> +    - **资产：** 当用户将新资产添加到场景中时，或加载场景时调用。
此处空格省略会把"****"显示到正文；
统一使用了中文冒号

2024-11-01 12:38 UTC, EcoFur commented on i18n/zh/docusaurus-plugin-content-docs/current/mocap/steamvr.md
> +如果要在蓝图中访问原始追踪器数据，可以使用 **获取SteamVR设备数据** 。此节点会返回指定 VR 设备（如追踪器、控制器、HMD）的位置和旋转。
我也强迫症………

2024-11-01 12:55 UTC, EcoFur commented
![image](https://github.com/user-attachments/assets/173a28b2-a9ee-4b71-8817-1d7899eb246f)
yarn start 之后，我参考别的文档时发现的

2024-11-01 14:33 UTC, EcoFur reviewed
修正错误

2024-11-01 14:33 UTC, EcoFur commented on docs/scripting/creating-your-first-script.md
> +    private long count;
int 饼干个数不够吃

2024-11-01 14:33 UTC, EcoFur commented on i18n/zh/docusaurus-plugin-content-docs/current/scripting/creating-your-first-script.md
> +    private long count;
int 饼干个数不够吃

2024-11-01 14:33 UTC, EcoFur commented on i18n/zh/docusaurus-plugin-content-docs/current/scripting/custom-asset.md
资产——>资源

2024-11-01 14:33 UTC, EcoFur commented on i18n/zh/docusaurus-plugin-content-docs/current/tutorials/readme-1.md
.md 在 yarn 运行后显示格式错误

2024-11-15 09:52 UTC, EcoFur commented on i18n/zh/docusaurus-plugin-content-docs/current/tutorials/readme-1.md
> +我们来欣赏一下刚刚加载好的模型吧。默认的摄像机模式是 **「环绕角色」**，也就是摄像机会绕着角色转。你可以**鼠标左键或右键**来旋转视角，**鼠标滚轮**来拉远拉近，**鼠标中键**来平移视角。试下将摄像机移动到这个角度吧：
在网页显示中出现问题

2024-11-15 09:54 UTC, EcoFur commented on i18n/zh/docusaurus-plugin-content-docs/current/tutorials/readme-1.md
> +摄像机除了可以绕着模型转以外，还可以切换成 **「自由观察」** 模式，直接在场景中穿梭飞行。选中摄像机资源，然后「控制模式」选择「自由观察」：
![382284436-173a28b2-a9ee-4b71-8817-1d7899eb246f](https://github.com/user-attachments/assets/1cf9c457-94a9-4485-af05-ea63a3b5060c)

2024-11-15 10:00 UTC, EcoFur commented on i18n/zh/docusaurus-plugin-content-docs/current/tutorials/readme-1.md
> +摄像机除了可以绕着模型转以外，还可以切换成 **「自由观察」** 模式，直接在场景中穿梭飞行。选中摄像机资源，然后「控制模式」选择「自由观察」：
![image](https://github.com/user-attachments/assets/6b2557af-fb32-49bf-816f-1bd924a51e39)

2024-11-17 10:31 UTC, EcoFur commented
我已经重新提交了代码，还有个冲突我无法解决


Sent from my Apple Watch

2024-11-22 10:33 UTC, hanekit commented
@EcoFur
翻译和修改都审完了，
我建了另外一个pr #88，解决了冲突然后润色了一点小细节。
这个 pr 就别动了，后续会关闭掉。
如果还有后续修改，可以等 #87 #88 合并之后，然后在最新版的基础上再进行修改！以免冲突。
感谢你对 Warudo Handbook 的贡献 ^v^ ~

2024-11-22 14:00 UTC, EcoFur commented
嘻嘻，第一个PR也算是被merge了。明天回家再仔细看看。     也感谢Tiger对我的支持。   <br>Have a good day. 


Sent from my Apple Watch

2024-11-22 23:55 UTC, EcoFur commented
……Tiger & Hane


Sent from my Apple Watch

2024-12-01 00:26 UTC, merged

2024-12-01 00:27 UTC, TigerHix commented
辛苦二位！！